version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: Naruto123!
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi\Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      ConnectionStrings__AnimeDbConnectionString: "Server=db;Database=AnimeDb;User Id=sa;Password=Naruto123!;TrustServerCertificate=True"